before_script:
    - sudo apt-get install gcc-arm-linux-gnueabi
    - export PATH=$(pwd)/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/bin:$PATH
    - export ARCH=arm
    - export SUBARCH=arm
    - export CROSS_COMPILE=arm-eabi-
script: ./make_kernel.sh hammerhead_defconfig arm-eabi-
